### ISSUE TITLE
Moodlegist Certificate Chain?

### ISSUE THREAD

**Issue by michaelwayneharris87** [CLAMP-IT/moodlegist#5]
When I try to run composer require, I get this error: 

```
The "https://moodlegist.clamp-it.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error   
  messages:                                                                                                                           
  error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed                                                
  Failed to enable crypto                                                                                                             
  failed to open stream: operation failed     
```

When I check the domain at https://whatsmychaincert.com, it tells me that there is an expired certificate in the trusted chain. 

I'm able to get things working by downloading the certificate and including that in my composer .json file as part of the repository definition: 

    "repositories": [
        {
            "type":"composer",
            "url":"https://moodlegist.clamp-it.org",
            "options": {
                "ssl": {
                    "cafile": "moodlegistrootca.crt"
                }
            }
        }
    ]

But, I'm not sure if this is something y'all could resolve?

**Comment by mackensen** [comment]
@michaelwayneharris87 thanks for the report. Yes, that's something we can address; we overlooked updating the Sectigo intermediate.

**Comment by mackensen** [comment]
This is fixed now.
